crypto: lz4hc: Fix compilation error caused by updating lz4
../crypto/lz4hc.c:56:10: error: use of undeclared identifier 'LZ4HC_DEFAULT_CLEVEL'
                *dlen, LZ4HC_DEFAULT_CLEVEL, ctx);
                       ^

Change-Id: 85514f1981157596cb34b016d69e37365bdfaedf
Signed-off-by: TogoFire <togofire@mailfence.com>
(cherry picked from commit ddc876b90ae501849e39e032d98f512a262d417e)
Signed-off-by: Madara273 <ravenhoxs@gmail.com>