usb: gadget: uvc: Fix vb2_qbuf too few arguments error
Log:
../drivers/usb/gadget/function/uvc-new/uvc_queue.c:196:36: error: too few arguments to function call, expected 3, have 2
  196 |         return vb2_qbuf(&queue->queue, buf);
      |                ~~~~~~~~                   ^
../include/media/videobuf2-v4l2.h:144:5: note: 'vb2_qbuf' declared here
  144 | int vb2_qbuf(struct vb2_queue *q, struct media_device *mdev,
      |     ^        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  145 |              struct v4l2_buffer *b);
      |              ~~~~~~~~~~~~~~~~~~~~~
1 error generated.

Change-Id: 41dccea57c651f30cff99a855d4404b58b965e79
Signed-off-by: TogoFire <togofire@mailfence.com>
(cherry picked from commit 3a382c62f13d687a2fa4844321ff969f46e745ea)
Signed-off-by: Madara273 <ravenhoxs@gmail.com>